from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session
from typing import List
from uuid import UUID
from app.database.database import get_db
from app.schemas.recommendation import RecommendationCreate, RecommendationResponse
from app.services.recommendation import RecommendationService
from app.api.dependencies import get_current_user
from app.models.user import User

router = APIRouter(prefix="/recommendations", tags=["Recommendations"])

@router.get("", response_model=List[RecommendationResponse], summary="List all recommendations for the user")
def list_recommendations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Fetch all optimization advice generated for the current user session.
    """
    service = RecommendationService(db)
    return service.list_recommendations(current_user.id)


@router.get("/unread", response_model=List[RecommendationResponse], summary="List unread recommendations")
def list_unread_recommendations(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Fetch all unread savings and optimization notifications.
    """
    service = RecommendationService(db)
    return service.list_unread_recommendations(current_user.id)


@router.get("/{id}", response_model=RecommendationResponse, summary="Get details for a specific recommendation")
def get_recommendation(
    id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Retrieve details for a specific recommendation UUID.
    """
    service = RecommendationService(db)
    return service.get_recommendation(id, current_user.id)


@router.post("", response_model=RecommendationResponse, status_code=status.HTTP_201_CREATED, summary="Create a recommendation record")
def create_recommendation(
    data: RecommendationCreate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Record advice generated by budget trigger engines.
    """
    service = RecommendationService(db)
    return service.create_recommendation(current_user.id, data)


@router.put("/{id}/read", response_model=RecommendationResponse, summary="Mark recommendation as read")
def mark_as_read(
    id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Mark an advice card as viewed/read.
    """
    service = RecommendationService(db)
    return service.mark_as_read(id, current_user.id)


@router.delete("/{id}", status_code=status.HTTP_200_OK, summary="Delete a recommendation record")
def delete_recommendation(
    id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Discard a recommendation advice card.
    """
    service = RecommendationService(db)
    service.delete_recommendation(id, current_user.id)
    return {"message": "Recommendation card deleted successfully."}
