"""Extend user profile fields

Revision ID: 3881f2c443f9
Revises: 87a111a9a85b
Create Date: 2026-07-18 13:54:51.627850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3881f2c443f9'
down_revision: Union[str, Sequence[str], None] = '87a111a9a85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('monthly_income', sa.Numeric(precision=15, scale=4), server_default=sa.text('0.0000'), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=50), server_default=sa.text("'English'"), nullable=False))
    op.add_column('users', sa.Column('profile_photo', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'language')
    op.drop_column('users', 'monthly_income')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
