import React from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, AlertCircle, CheckCircle2, Info, Lightbulb, ArrowUpRight } from 'lucide-react';

const SEVERITY_STYLES = {
  DANGER: {
    bg: 'bg-rose-500/10 border-rose-500/30 text-rose-400',
    badge: 'bg-rose-500/20 text-rose-400',
    icon: AlertTriangle,
  },
  WARNING: {
    bg: 'bg-amber-500/10 border-amber-500/30 text-amber-400',
    badge: 'bg-amber-500/20 text-amber-400',
    icon: AlertCircle,
  },
  SUCCESS: {
    bg: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400',
    badge: 'bg-emerald-500/20 text-emerald-400',
    icon: CheckCircle2,
  },
  INFO: {
    bg: 'bg-indigo-500/10 border-indigo-500/30 text-indigo-400',
    badge: 'bg-indigo-500/20 text-indigo-400',
    icon: Info,
  },
};

export const TrendCard = ({ smartWarnings = [], loading }) => {
  if (loading) {
    return (
      <div className="animate-pulse p-6 rounded-3xl border border-border-subtle bg-bg-surface space-y-3">
        <div className="h-4 bg-slate-800 rounded w-1/3" />
        <div className="h-20 bg-slate-800/60 rounded-2xl" />
      </div>
    );
  }

  if (!smartWarnings || smartWarnings.length === 0) {
    return (
      <div className="rounded-3xl border border-border-subtle bg-bg-surface p-6 shadow-glass backdrop-blur-xl space-y-3 flex flex-col items-center justify-center text-center">
        <div className="p-2.5 rounded-2xl bg-primary-500/10 text-primary-400">
          <Lightbulb className="w-5 h-5" />
        </div>
        <h4 className="text-sm font-bold text-white font-outfit">No AI Risk Anomalies Detected</h4>
        <p className="text-xs text-slate-400 max-w-sm">
          Meta Prophet evaluated your transaction forecast and detected zero spending risk anomalies or liquidity deficits for this period.
        </p>
      </div>
    );
  }

  const warnings = smartWarnings;

  return (
    <div className="rounded-3xl border border-border-subtle bg-bg-surface p-6 shadow-glass backdrop-blur-xl space-y-4">
      <div className="flex items-center gap-2">
        <div className="p-2 rounded-2xl bg-primary-500/10 text-primary-400">
          <Lightbulb className="w-4 h-4" />
        </div>
        <div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white font-outfit">
            AI Business Insights & Smart Warnings
          </h3>
          <p className="text-xs text-slate-400">
            Real-time trajectory analysis and anomaly detection generated by Meta Prophet
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {warnings.map((w, idx) => {
          const config = SEVERITY_STYLES[w.severity] || SEVERITY_STYLES.INFO;
          const Icon = config.icon;

          return (
            <motion.div
              key={w.id || idx}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, delay: idx * 0.08 }}
              className={`rounded-2xl border p-4 backdrop-blur-md space-y-2.5 ${config.bg}`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center gap-2">
                  <Icon className="w-4 h-4 shrink-0" />
                  <h4 className="text-xs font-extrabold text-white font-outfit">
                    {w.title}
                  </h4>
                </div>
                <span className={`px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider shrink-0 ${config.badge}`}>
                  {w.severity}
                </span>
              </div>

              <p className="text-xs text-slate-300 font-normal leading-relaxed">
                {w.message}
              </p>

              {w.recommendation && (
                <div className="pt-2 border-t border-white/10 flex items-start gap-1.5 text-[11px] text-slate-200">
                  <ArrowUpRight className="w-3.5 h-3.5 text-primary-400 shrink-0 mt-0.5" />
                  <span><strong>AI Rec:</strong> {w.recommendation}</span>
                </div>
              )}
            </motion.div>
          );
        })}
      </div>
    </div>
  );
};

export default TrendCard;
